# Generated by Django 4.1.5 on 2023-02-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
