# Generated by Django 4.1.5 on 2023-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_login_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_data',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
