# Generated by Django 4.1.5 on 2023-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_login_data_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='date_birth',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
