# Generated by Django 4.1.5 on 2023-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_admin_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
