# Generated by Django 4.1.5 on 2023-02-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_alter_register_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='study',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
