# Generated by Django 4.1.5 on 2023-02-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_alter_deleted_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
